---
title: "Multisystemfunktionalität von R Paketen"
author: "Clemens Schmid"
date: "20. Oktober 2016"
output:
  html_document:
    theme: "spacelab"
---

## Problemstellung

#### Prolog

* R Paket [recexcavAAR](https://CRAN.R-project.org/package=recexcavAAR)
    * Fragestellung, Funktionen und warum ist das nützlich?
    * Rcpp
    * automatisierte Tests
    * Vignettes
    * **CRAN** (Comprehensive R Archive Network)
        * Vorbereitung
        * Kommunikation
        * **Multisystemfunktionalität**

* Multisystemfunktionalität ist mein jüngstes Problem - am deutlichsten präsent und am wenigsten verstanden. 

* These: Viele Fehler sind durch gute Vorbereitung und Checks vermeidbar.
        
#### Problemstellung

* **Ein R Paket muss auf möglichst vielen Zielsystemen lauffähig sein.** 

* Probleme
    * OS (Mac OS, Windows, Linux, Solaris?!)
    * R Version + R-devel vs. R-release
    * Fremdpakete und Abhängigkeiten

* CRAN Checks
    * [CRAN Check Systeme](https://cran.r-project.org/web/checks/check_flavors.html) 
    * [recexcavAAR Check Ergebnisse](https://cran.r-project.org/web/checks/check_results_recexcavAAR.html)

#### Beispiel 1: Solaris 'overloading ambiguity' 

### FALSCH:
```{c, eval=FALSE}
int lres2 = pow(lres, 2);
int lres3 = pow(lres, 3);
```

> Mathematical functions such as sqrt are defined in C++ for floating-point arguments. It is legitimate in C++ to overload these with versions for types float, double, long double and possibly more. **This means that calling sqrt on an integer type may have ‘overloading ambiguity’ as it could be promoted to any of the supported floating-point types: this is commonly seen on Solaris**, but for pow also seen on OS X. (C++98 has an overload for std::pow(<double>, <int>), but this may not be visible from the main namespace. C++11 requires additional overloads for integer types, and ambiguous overloads are more common in C++11 (and later) compiler modes.) 
>
> **-- CRAN: Writing R Extensions §1.6.4**

### RICHTIG: Type conversion
```{c, eval=FALSE}
int lres2 = pow((double)lres, 2.0);
int lres3 = pow((double)lres, 3.0);
```

#### Beispiel 2: plotly Versionsupdate (Vignette)

### FALSCH:
```{r, eval=FALSE}
libary(plotly)

vis %>% 
  add_trace(
    x = surf[[1]]$x, y = surf[[1]]$y, z = surf[[1]]$z, type = "surface", 
    showscale = FALSE, opacity = 0.9, hoverinfo = "none"
  )
```

[**Github Issue**](https://github.com/ropensci/plotly/issues/756)

### RICHTIG:
```{R, eval=FALSE}
library(rgl)

surface3d(
    surf[[i]]$x, surf[[i]]$y, t(surf[[i]]$z),
    color = c("black", "white"),
    alpha = 0.5,
    add = TRUE
  )
```



## Lösungsansätze

#### Lösungsansätze

* Vorbereitung
    * [Hadley Wickhams Anleitung](http://r-pkgs.had.co.nz/)
    * [Anleitungen des R Development Core Team](https://cran.r-project.org/) -> Manuals -> Writing R Extensions

* Workflow
    * testthat
    * roxygen2
    * **devtools** (```devtools::check_cran()```)
    * etc.

* Testumgebungen
    * [Travis CI](https://travis-ci.org/) (recexcavAAR: [webGUI](https://travis-ci.org/ISAAKiel/recexcavAAR) + [.travis.yml](https://github.com/ISAAKiel/recexcavAAR/blob/master/.travis.yml))
    * eigene virtuelle Maschinen (siehe virtual box solaris)
    * [Winbuilder](http://win-builder.r-project.org/) (```devtools::build_win()```)
    * [Rocker](https://github.com/rocker-org/rocker)?
    * **ISAAK: Web of Czechs?**
