---
title: "Events"
output:
  html_document:
    theme: "spacelab"
    css: other_page_styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Events by and with members of ISAAK

<div class="row">

```{r echo = FALSE}
#### read events list ####
events <- read.csv("data/events_list.csv", header = TRUE, stringsAsFactors = FALSE)
events <- events[order(events$year, events$month, decreasing = TRUE), ]
events$month <- month.name[events$month]
```

```{r results = 'asis', echo = FALSE}
#### textoutput ####
for (i in 1:nrow(events)){
  cat('<div class="col-xs-6 col-sm-3">')
  cat('<div class="card">')
  cat('<div class="card-content"><h4 class="card-title">')
  title_string <- events$title[i]
  cat('<a href="', events$url[i], '" style="color:#345578;">', title_string, "</a></h4><br/>")
  cat('<div class="">')
  cat(events$month[i], events$year[i])
  cat("<br><br>")
  cat(events$description[i])
  cat('</div>')
  cat('</div>')
  cat('</div>')
  cat('</div>')
}
```

</div>
