---
output:
  html_document:
    css: frontpage_styles.css
    theme: "spacelab"
    includes:
      in_header: header.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Scope
Archaeoinformatics, computational archaeology and quantitative methods are a constant and developing branch since the last decades. It comprises different aspects of archaeology and information technology in daily work as well as methodology. Both - the use of the current technology and the methodological implementation in archaeology - has to be developed. This is the aim of our working group.

## Who we are
We are archaeologists developing IT solutions and statistical tools in and for our work activly envolved in the following institutions:

* [Institut für Ur- und Frühgeschichte, Christian-Albrechts-Universität zu Kiel](https://www.ufg.uni-kiel.de/)
* [Niedersächsisches Institut für historische Küstenforschung, Wilhelmshafen](http://www.nihk.de/)
* [eScience-Center Tübingen](https://www.uni-tuebingen.de/einrichtungen/informations-kommunikations-und-medienzentrum-ikm/escience-center.html)

## What we do and offer:
We offer programs, scripts and functions for data management and interoperability, develop R-packages for different tasks and present tutorials for programs and archaeological tasks. Everything in constant development and freely accessible in our github repository.

Currently we work on this topics:

* statistical and quantitative methods
* spatial analysis
* data bases and data management
* mapping and remote sensing
* simulation and reconstruction
* open data and open publishing

To see our current portfolio, visit the [projects](projects.html) page.

## Would you like to participate?

Feel free to [fork][fork] a repository, submit an [issue][issue], or contact us, if you are interested to join our group.

[fork]: http://help.github.com/fork-a-repo/
[issue]: https://help.github.com/articles/creating-an-issue/
  